# Check out https://docs.codemagic.io/yaml/yaml/ for more information
# Please review and update values in curly braces

workflows:
    android-flutter:
        name: Android App(Geets) with Flutter Module
        environment:
            vars:
                FLUTTER_MODULE_DIR: "/home/shashi/Projects/flutter/Geets"
                HOST_ANDROID_APP_DIR: "/home/shashi/flutter/Geets/android"
            flutter: stable
        scripts:
            - echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
            - cd $FLUTTER_MODULE_DIR && flutter pub get
            - cd $HOST_ANDROID_APP_DIR && ./gradlew assembleDebug
        artifacts:
            - $HOST_ANDROID_APP_DIR/app/build/outputs/**/**/*.apk